# Generated by Django 5.0.2 on 2024-04-29 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Username', models.CharField(blank=True, max_length=100, unique=True)),
                ('Password', models.CharField(blank=True, max_length=100)),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffsignup.branch')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
            },
        ),
        migrations.CreateModel(
            name='FieldHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('add', 'Add'), ('edit', 'Edit')], max_length=10)),
                ('model_name', models.CharField(max_length=20)),
                ('coaching_roll', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffsignup.staff')),
            ],
        ),
        migrations.CreateModel(
            name='DisplayPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffsignup.staff')),
            ],
            options={
                'verbose_name': 'Display Preference',
                'verbose_name_plural': 'Display Preferences',
            },
        ),
        migrations.CreateModel(
            name='StaffDetailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_added', models.PositiveIntegerField(default=0)),
                ('details_added_flag', models.BooleanField(default=False)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staffsignup.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoachingRegisteration', models.BigIntegerField()),
                ('CoachingRoll', models.BigIntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('FatherName', models.CharField(blank=True, max_length=100)),
                ('MotherName', models.CharField(max_length=100)),
                ('PrimaryNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('SecondaryNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('AdditionalNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('WhatsappNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('Course', models.CharField(max_length=100)),
                ('CourseId', models.IntegerField()),
                ('Batch', models.CharField(max_length=100)),
                ('Medium', models.CharField(max_length=100)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=500)),
                ('Tehsil', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('PreviousRoll', models.CharField(blank=True, max_length=100, null=True)),
                ('Exam', models.CharField(max_length=100)),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffsignup.branch')),
            ],
            options={
                'verbose_name': 'Student Details',
                'verbose_name_plural': 'Student Details',
            },
        ),
        migrations.CreateModel(
            name='NEETRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NEETApplication', models.BigIntegerField(blank=True, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Category', models.CharField(blank=True, max_length=50, null=True)),
                ('StudentDetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staffsignup.studentdetails')),
            ],
            options={
                'verbose_name': 'NEET Registrations',
                'verbose_name_plural': 'NEET Registrations',
            },
        ),
        migrations.CreateModel(
            name='JEEMAIN1Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JEEMAIN1Application', models.BigIntegerField(blank=True, null=True)),
                ('Mobile', models.BigIntegerField(blank=True, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('StudentDetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staffsignup.studentdetails')),
            ],
            options={
                'verbose_name': 'JEE Main 1 Registrations',
                'verbose_name_plural': 'JEE Main 1 Registrations',
            },
        ),
    ]
