# Generated by Django 5.0.2 on 2024-04-29 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JeeAdvReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdvanceRegNo', models.CharField(blank=True, max_length=252, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Mobile', models.BigIntegerField(blank=True, null=True)),
                ('StudentDetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staffsignup.studentdetails')),
            ],
            options={
                'verbose_name': 'JEE Advanced Registrations',
                'verbose_name_plural': 'JEE Advanced Registrations',
            },
        ),
    ]
