# Generated by Django 5.0.2 on 2024-04-06 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='Exam',
        ),
    ]
