# Generated by Django 5.0.2 on 2024-03-01 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0002_branch_rename_password_staff_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffsignup.branch'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='Branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffsignup.branch'),
        ),
    ]
