# Generated by Django 5.0.2 on 2024-04-30 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0002_jeeadvreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEETCityIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NEETApplication', models.CharField(blank=True, max_length=252, null=True)),
                ('Name', models.CharField(blank=True, max_length=252, null=True)),
                ('FatherName', models.CharField(blank=True, max_length=252, null=True)),
                ('Category', models.CharField(blank=True, max_length=252, null=True)),
                ('Pwd', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('City', models.CharField(blank=True, max_length=252, null=True)),
                ('State', models.CharField(blank=True, max_length=252, null=True)),
                ('StudentDetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staffsignup.studentdetails')),
            ],
            options={
                'verbose_name': 'Student City Intimation',
                'verbose_name_plural': 'Students City Intimation',
            },
        ),
    ]
