# Generated by Django 5.0.2 on 2024-03-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0003_alter_staff_branch_alter_staff_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Name',
            new_name='Username',
        ),
    ]
