# Generated by Django 5.0.2 on 2024-04-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0003_remove_studentdetails_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='CourseType',
            field=models.CharField(default='NEET', max_length=100),
            preserve_default=False,
        ),
    ]
