# Generated by Django 5.0.2 on 2024-03-04 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0004_rename_name_staff_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffsignup.staff')),
            ],
        ),
        migrations.CreateModel(
            name='NEETRegisteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NEETApplication', models.IntegerField()),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('StudentDetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staffsignup.studentdetails')),
            ],
        ),
    ]
