# Generated by Django 5.0.2 on 2024-04-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0004_studentdetails_coursetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetails',
            old_name='CourseType',
            new_name='Exam',
        ),
    ]
