# Generated by Django 5.0.2 on 2024-04-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0004_alter_neetcityin_options_neetcityin_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neetcityin',
            name='DOB',
        ),
        migrations.AlterField(
            model_name='neetcityin',
            name='Pwd',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
