# Generated by Django 5.0.2 on 2024-05-03 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0005_remove_neetcityin_dob_alter_neetcityin_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemarkStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('StudentDetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staffsignup.studentdetails')),
            ],
            options={
                'verbose_name': 'Student Remarks',
                'verbose_name_plural': 'Student Remarks',
            },
        ),
    ]
