# Generated by Django 5.0.2 on 2024-04-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0005_rename_coursetype_studentdetails_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='PreviousRoll',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
