# Generated by Django 5.0.2 on 2024-04-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0006_alter_studentdetails_previousroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
