# Generated by Django 5.0.2 on 2024-03-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0006_alter_neetregisteration_mobile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NEETRegisteration',
            new_name='NEETRegistration',
        ),
    ]
