# Generated by Django 5.0.2 on 2024-05-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0006_remarkstudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='remarkstudents',
            name='CoachingRoll',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
