# Generated by Django 5.0.2 on 2024-03-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0007_rename_neetregisteration_neetregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neetregistration',
            name='NEETApplication',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
