# Generated by Django 5.0.2 on 2024-04-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0007_alter_studentdetails_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='FatherName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
