# Generated by Django 5.0.2 on 2024-03-15 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0008_alter_neetregistration_neetapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='JEEMAIN1Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JEEMAIN1Application', models.BigIntegerField(blank=True, null=True)),
                ('Mobile', models.BigIntegerField(blank=True, null=True)),
                ('StudentDetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staffsignup.studentdetails')),
            ],
        ),
    ]
