# Generated by Django 5.0.2 on 2024-04-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0008_alter_studentdetails_fathername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='Pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
