# Generated by Django 5.0.2 on 2024-03-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0009_jeemain1registration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jeemain1registration',
            options={'verbose_name': 'JEEMAIN1 Registration', 'verbose_name_plural': 'JEEMAIN1 Registrations'},
        ),
    ]
