# Generated by Django 5.0.2 on 2024-04-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0009_alter_studentdetails_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='Pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
