# Generated by Django 5.0.2 on 2024-04-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0010_alter_studentdetails_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='neetregistration',
            name='Category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='neetregistration',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
