# Generated by Django 5.0.2 on 2024-03-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0010_alter_jeemain1registration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='displaypreference',
            options={'verbose_name': 'Display Preference', 'verbose_name_plural': 'Display Preferences'},
        ),
        migrations.AlterModelOptions(
            name='jeemain1registration',
            options={'verbose_name': 'JEE MAIN 1 Registration', 'verbose_name_plural': 'JEE MAIN 1 Registrations'},
        ),
        migrations.AlterModelOptions(
            name='neetregistration',
            options={'verbose_name': 'NEET Registrations', 'verbose_name_plural': 'NEET Registrations'},
        ),
        migrations.AlterModelOptions(
            name='studentdetails',
            options={'verbose_name': 'Student Details', 'verbose_name_plural': 'Student Details'},
        ),
    ]
