# Generated by Django 5.0.2 on 2024-03-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0011_alter_branch_options_alter_displaypreference_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jeemain1registration',
            options={'verbose_name': 'JEE Main 1 Registrations', 'verbose_name_plural': 'JEE Main 1 Registrations'},
        ),
    ]
