# Generated by Django 5.0.2 on 2024-04-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0011_neetregistration_category_neetregistration_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neetregistration',
            name='Mobile',
        ),
    ]
