# Generated by Django 5.0.2 on 2024-03-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0012_alter_jeemain1registration_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jeemain1registration',
            old_name='StudentDetails',
            new_name='StudentDetail',
        ),
    ]
