# Generated by Django 5.0.2 on 2024-04-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0012_alter_jeemain1registration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staffs'},
        ),
        migrations.RenameField(
            model_name='jeemain1registration',
            old_name='StudentDetails',
            new_name='StudentDetail',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='CourseType',
            new_name='Exam',
        ),
        migrations.RemoveField(
            model_name='neetregistration',
            name='Mobile',
        ),
        migrations.AddField(
            model_name='jeemain1registration',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neetregistration',
            name='Category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='neetregistration',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='Name',
            field=models.CharField(default='Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='AdditionalNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='Pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='PrimaryNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='SecondaryNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='WhatsappNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='CoachingRegisteration',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='CoachingRoll',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='FatherName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='PreviousRoll',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
