# Generated by Django 5.0.2 on 2024-04-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0012_remove_neetregistration_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeemain1registration',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
