# Generated by Django 5.0.2 on 2024-03-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0013_rename_studentdetails_jeemain1registration_studentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeemain1registration',
            name='Num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
