# Generated by Django 5.0.2 on 2024-04-12 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0013_alter_staff_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDetailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_added', models.PositiveIntegerField(default=0)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staffsignup.staff')),
            ],
        ),
    ]
