# Generated by Django 5.0.2 on 2024-03-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0014_jeemain1registration_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jeemain1registration',
            name='Num',
        ),
    ]
