# Generated by Django 5.0.2 on 2024-04-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0014_staffdetailtracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetailtracking',
            name='details_added_flag',
            field=models.BooleanField(default=False),
        ),
    ]
