# Generated by Django 5.0.3 on 2024-03-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0015_remove_jeemain1registration_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staffs'},
        ),
        migrations.AddField(
            model_name='staff',
            name='Name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='Password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
