# Generated by Django 5.0.3 on 2024-03-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0016_alter_staff_options_staff_name_alter_staff_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
