# Generated by Django 5.0.2 on 2024-04-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0016_fieldhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldhistory',
            name='coaching_roll',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldhistory',
            name='model_name',
            field=models.CharField(default='Neet', max_length=20),
            preserve_default=False,
        ),
    ]
