# Generated by Django 5.0.2 on 2024-04-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0017_fieldhistory_coaching_roll_fieldhistory_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldhistory',
            name='action',
            field=models.CharField(choices=[('add', 'Add'), ('edit', 'Edit')], max_length=10),
        ),
    ]
