# Generated by Django 5.0.2 on 2024-04-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsignup', '0018_alter_fieldhistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldhistory',
            name='old_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
